/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.beathoven.BeathovenRuntimeModule;
import org.beathoven.BeathovenStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BeathovenIdeSetup extends BeathovenStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BeathovenRuntimeModule(), new BeathovenIdeModule()));
	}
	
}
