/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven.impl;

import java.util.Collection;

import org.beathoven.beathoven.BeathovenPackage;
import org.beathoven.beathoven.Chord;
import org.beathoven.beathoven.Duration;
import org.beathoven.beathoven.NoteValue;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Chord</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.impl.ChordImpl#getChord <em>Chord</em>}</li>
 *   <li>{@link org.beathoven.beathoven.impl.ChordImpl#getNotes <em>Notes</em>}</li>
 *   <li>{@link org.beathoven.beathoven.impl.ChordImpl#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChordImpl extends BlockImpl implements Chord
{
  /**
   * The default value of the '{@link #getChord() <em>Chord</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChord()
   * @generated
   * @ordered
   */
  protected static final String CHORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getChord() <em>Chord</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChord()
   * @generated
   * @ordered
   */
  protected String chord = CHORD_EDEFAULT;

  /**
   * The cached value of the '{@link #getNotes() <em>Notes</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNotes()
   * @generated
   * @ordered
   */
  protected EList<NoteValue> notes;

  /**
   * The cached value of the '{@link #getDuration() <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDuration()
   * @generated
   * @ordered
   */
  protected Duration duration;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChordImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return BeathovenPackage.Literals.CHORD;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getChord()
  {
    return chord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setChord(String newChord)
  {
    String oldChord = chord;
    chord = newChord;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BeathovenPackage.CHORD__CHORD, oldChord, chord));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<NoteValue> getNotes()
  {
    if (notes == null)
    {
      notes = new EObjectContainmentEList<NoteValue>(NoteValue.class, this, BeathovenPackage.CHORD__NOTES);
    }
    return notes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Duration getDuration()
  {
    return duration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetDuration(Duration newDuration, NotificationChain msgs)
  {
    Duration oldDuration = duration;
    duration = newDuration;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, BeathovenPackage.CHORD__DURATION, oldDuration, newDuration);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setDuration(Duration newDuration)
  {
    if (newDuration != duration)
    {
      NotificationChain msgs = null;
      if (duration != null)
        msgs = ((InternalEObject)duration).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - BeathovenPackage.CHORD__DURATION, null, msgs);
      if (newDuration != null)
        msgs = ((InternalEObject)newDuration).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - BeathovenPackage.CHORD__DURATION, null, msgs);
      msgs = basicSetDuration(newDuration, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, BeathovenPackage.CHORD__DURATION, newDuration, newDuration));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case BeathovenPackage.CHORD__NOTES:
        return ((InternalEList<?>)getNotes()).basicRemove(otherEnd, msgs);
      case BeathovenPackage.CHORD__DURATION:
        return basicSetDuration(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case BeathovenPackage.CHORD__CHORD:
        return getChord();
      case BeathovenPackage.CHORD__NOTES:
        return getNotes();
      case BeathovenPackage.CHORD__DURATION:
        return getDuration();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case BeathovenPackage.CHORD__CHORD:
        setChord((String)newValue);
        return;
      case BeathovenPackage.CHORD__NOTES:
        getNotes().clear();
        getNotes().addAll((Collection<? extends NoteValue>)newValue);
        return;
      case BeathovenPackage.CHORD__DURATION:
        setDuration((Duration)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case BeathovenPackage.CHORD__CHORD:
        setChord(CHORD_EDEFAULT);
        return;
      case BeathovenPackage.CHORD__NOTES:
        getNotes().clear();
        return;
      case BeathovenPackage.CHORD__DURATION:
        setDuration((Duration)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case BeathovenPackage.CHORD__CHORD:
        return CHORD_EDEFAULT == null ? chord != null : !CHORD_EDEFAULT.equals(chord);
      case BeathovenPackage.CHORD__NOTES:
        return notes != null && !notes.isEmpty();
      case BeathovenPackage.CHORD__DURATION:
        return duration != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (chord: ");
    result.append(chord);
    result.append(')');
    return result.toString();
  }

} //ChordImpl
