/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.parser.antlr;

import com.google.inject.Inject;
import org.beathoven.parser.antlr.internal.InternalBeathovenParser;
import org.beathoven.services.BeathovenGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class BeathovenParser extends AbstractAntlrParser {

	@Inject
	private BeathovenGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalBeathovenParser createParser(XtextTokenStream stream) {
		return new InternalBeathovenParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public BeathovenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(BeathovenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
