/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.beathoven.beathoven.BeathovenFactory
 * @model kind="package"
 * @generated
 */
public interface BeathovenPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "beathoven";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.beathoven.org/Beathoven";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "beathoven";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  BeathovenPackage eINSTANCE = org.beathoven.beathoven.impl.BeathovenPackageImpl.init();

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.ModelImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__BLOCKS = 0;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.BlockImpl <em>Block</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.BlockImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getBlock()
   * @generated
   */
  int BLOCK = 1;

  /**
   * The number of structural features of the '<em>Block</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BLOCK_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.TempoImpl <em>Tempo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.TempoImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTempo()
   * @generated
   */
  int TEMPO = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPO__VALUE = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Tempo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPO_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.TimeImpl <em>Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.TimeImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTime()
   * @generated
   */
  int TIME = 3;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME__VALUE = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.KeyImpl <em>Key</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.KeyImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getKey()
   * @generated
   */
  int KEY = 4;

  /**
   * The feature id for the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY__NOTE = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Key</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int KEY_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.TitleImpl <em>Title</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.TitleImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTitle()
   * @generated
   */
  int TITLE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE__NAME = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Title</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TITLE_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.InstrumentImpl <em>Instrument</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.InstrumentImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getInstrument()
   * @generated
   */
  int INSTRUMENT = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUMENT__NAME = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Instrument</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUMENT_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.NoteStmtImpl <em>Note Stmt</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.NoteStmtImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getNoteStmt()
   * @generated
   */
  int NOTE_STMT = 7;

  /**
   * The feature id for the '<em><b>Pitch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_STMT__PITCH = BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_STMT__DURATION = BLOCK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Note Stmt</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_STMT_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.RestImpl <em>Rest</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.RestImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getRest()
   * @generated
   */
  int REST = 8;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST__DURATION = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rest</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REST_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.ChordImpl <em>Chord</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.ChordImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getChord()
   * @generated
   */
  int CHORD = 9;

  /**
   * The feature id for the '<em><b>Chord</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHORD__CHORD = BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Notes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHORD__NOTES = BLOCK_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHORD__DURATION = BLOCK_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Chord</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CHORD_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.RepeatImpl <em>Repeat</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.RepeatImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getRepeat()
   * @generated
   */
  int REPEAT = 10;

  /**
   * The feature id for the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT__TIMES = BLOCK_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Blocks</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT__BLOCKS = BLOCK_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Repeat</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REPEAT_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.MarkImpl <em>Mark</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.MarkImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getMark()
   * @generated
   */
  int MARK = 11;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARK__LABEL = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Mark</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MARK_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.GotoImpl <em>Goto</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.GotoImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getGoto()
   * @generated
   */
  int GOTO = 12;

  /**
   * The feature id for the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO__LABEL = BLOCK_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Goto</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GOTO_FEATURE_COUNT = BLOCK_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.NoteValueImpl <em>Note Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.NoteValueImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getNoteValue()
   * @generated
   */
  int NOTE_VALUE = 13;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_VALUE__VALUE = 0;

  /**
   * The number of structural features of the '<em>Note Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOTE_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.beathoven.beathoven.impl.DurationImpl <em>Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.beathoven.beathoven.impl.DurationImpl
   * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getDuration()
   * @generated
   */
  int DURATION = 14;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION__VALUE = 0;

  /**
   * The number of structural features of the '<em>Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DURATION_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see org.beathoven.beathoven.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.beathoven.beathoven.Model#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see org.beathoven.beathoven.Model#getBlocks()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Blocks();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Block <em>Block</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Block</em>'.
   * @see org.beathoven.beathoven.Block
   * @generated
   */
  EClass getBlock();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Tempo <em>Tempo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tempo</em>'.
   * @see org.beathoven.beathoven.Tempo
   * @generated
   */
  EClass getTempo();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Tempo#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.beathoven.beathoven.Tempo#getValue()
   * @see #getTempo()
   * @generated
   */
  EAttribute getTempo_Value();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Time <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time</em>'.
   * @see org.beathoven.beathoven.Time
   * @generated
   */
  EClass getTime();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Time#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.beathoven.beathoven.Time#getValue()
   * @see #getTime()
   * @generated
   */
  EAttribute getTime_Value();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Key <em>Key</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Key</em>'.
   * @see org.beathoven.beathoven.Key
   * @generated
   */
  EClass getKey();

  /**
   * Returns the meta object for the containment reference '{@link org.beathoven.beathoven.Key#getNote <em>Note</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Note</em>'.
   * @see org.beathoven.beathoven.Key#getNote()
   * @see #getKey()
   * @generated
   */
  EReference getKey_Note();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Title <em>Title</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Title</em>'.
   * @see org.beathoven.beathoven.Title
   * @generated
   */
  EClass getTitle();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Title#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.beathoven.beathoven.Title#getName()
   * @see #getTitle()
   * @generated
   */
  EAttribute getTitle_Name();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Instrument <em>Instrument</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instrument</em>'.
   * @see org.beathoven.beathoven.Instrument
   * @generated
   */
  EClass getInstrument();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Instrument#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.beathoven.beathoven.Instrument#getName()
   * @see #getInstrument()
   * @generated
   */
  EAttribute getInstrument_Name();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.NoteStmt <em>Note Stmt</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Note Stmt</em>'.
   * @see org.beathoven.beathoven.NoteStmt
   * @generated
   */
  EClass getNoteStmt();

  /**
   * Returns the meta object for the containment reference '{@link org.beathoven.beathoven.NoteStmt#getPitch <em>Pitch</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pitch</em>'.
   * @see org.beathoven.beathoven.NoteStmt#getPitch()
   * @see #getNoteStmt()
   * @generated
   */
  EReference getNoteStmt_Pitch();

  /**
   * Returns the meta object for the containment reference '{@link org.beathoven.beathoven.NoteStmt#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see org.beathoven.beathoven.NoteStmt#getDuration()
   * @see #getNoteStmt()
   * @generated
   */
  EReference getNoteStmt_Duration();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Rest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rest</em>'.
   * @see org.beathoven.beathoven.Rest
   * @generated
   */
  EClass getRest();

  /**
   * Returns the meta object for the containment reference '{@link org.beathoven.beathoven.Rest#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see org.beathoven.beathoven.Rest#getDuration()
   * @see #getRest()
   * @generated
   */
  EReference getRest_Duration();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Chord <em>Chord</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Chord</em>'.
   * @see org.beathoven.beathoven.Chord
   * @generated
   */
  EClass getChord();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Chord#getChord <em>Chord</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Chord</em>'.
   * @see org.beathoven.beathoven.Chord#getChord()
   * @see #getChord()
   * @generated
   */
  EAttribute getChord_Chord();

  /**
   * Returns the meta object for the containment reference list '{@link org.beathoven.beathoven.Chord#getNotes <em>Notes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Notes</em>'.
   * @see org.beathoven.beathoven.Chord#getNotes()
   * @see #getChord()
   * @generated
   */
  EReference getChord_Notes();

  /**
   * Returns the meta object for the containment reference '{@link org.beathoven.beathoven.Chord#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Duration</em>'.
   * @see org.beathoven.beathoven.Chord#getDuration()
   * @see #getChord()
   * @generated
   */
  EReference getChord_Duration();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Repeat <em>Repeat</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Repeat</em>'.
   * @see org.beathoven.beathoven.Repeat
   * @generated
   */
  EClass getRepeat();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Repeat#getTimes <em>Times</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Times</em>'.
   * @see org.beathoven.beathoven.Repeat#getTimes()
   * @see #getRepeat()
   * @generated
   */
  EAttribute getRepeat_Times();

  /**
   * Returns the meta object for the containment reference list '{@link org.beathoven.beathoven.Repeat#getBlocks <em>Blocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Blocks</em>'.
   * @see org.beathoven.beathoven.Repeat#getBlocks()
   * @see #getRepeat()
   * @generated
   */
  EReference getRepeat_Blocks();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Mark <em>Mark</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mark</em>'.
   * @see org.beathoven.beathoven.Mark
   * @generated
   */
  EClass getMark();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Mark#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.beathoven.beathoven.Mark#getLabel()
   * @see #getMark()
   * @generated
   */
  EAttribute getMark_Label();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Goto <em>Goto</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Goto</em>'.
   * @see org.beathoven.beathoven.Goto
   * @generated
   */
  EClass getGoto();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Goto#getLabel <em>Label</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Label</em>'.
   * @see org.beathoven.beathoven.Goto#getLabel()
   * @see #getGoto()
   * @generated
   */
  EAttribute getGoto_Label();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.NoteValue <em>Note Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Note Value</em>'.
   * @see org.beathoven.beathoven.NoteValue
   * @generated
   */
  EClass getNoteValue();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.NoteValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.beathoven.beathoven.NoteValue#getValue()
   * @see #getNoteValue()
   * @generated
   */
  EAttribute getNoteValue_Value();

  /**
   * Returns the meta object for class '{@link org.beathoven.beathoven.Duration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Duration</em>'.
   * @see org.beathoven.beathoven.Duration
   * @generated
   */
  EClass getDuration();

  /**
   * Returns the meta object for the attribute '{@link org.beathoven.beathoven.Duration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.beathoven.beathoven.Duration#getValue()
   * @see #getDuration()
   * @generated
   */
  EAttribute getDuration_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  BeathovenFactory getBeathovenFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.ModelImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__BLOCKS = eINSTANCE.getModel_Blocks();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.BlockImpl <em>Block</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.BlockImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getBlock()
     * @generated
     */
    EClass BLOCK = eINSTANCE.getBlock();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.TempoImpl <em>Tempo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.TempoImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTempo()
     * @generated
     */
    EClass TEMPO = eINSTANCE.getTempo();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPO__VALUE = eINSTANCE.getTempo_Value();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.TimeImpl <em>Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.TimeImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTime()
     * @generated
     */
    EClass TIME = eINSTANCE.getTime();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME__VALUE = eINSTANCE.getTime_Value();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.KeyImpl <em>Key</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.KeyImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getKey()
     * @generated
     */
    EClass KEY = eINSTANCE.getKey();

    /**
     * The meta object literal for the '<em><b>Note</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference KEY__NOTE = eINSTANCE.getKey_Note();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.TitleImpl <em>Title</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.TitleImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getTitle()
     * @generated
     */
    EClass TITLE = eINSTANCE.getTitle();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TITLE__NAME = eINSTANCE.getTitle_Name();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.InstrumentImpl <em>Instrument</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.InstrumentImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getInstrument()
     * @generated
     */
    EClass INSTRUMENT = eINSTANCE.getInstrument();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INSTRUMENT__NAME = eINSTANCE.getInstrument_Name();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.NoteStmtImpl <em>Note Stmt</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.NoteStmtImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getNoteStmt()
     * @generated
     */
    EClass NOTE_STMT = eINSTANCE.getNoteStmt();

    /**
     * The meta object literal for the '<em><b>Pitch</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTE_STMT__PITCH = eINSTANCE.getNoteStmt_Pitch();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOTE_STMT__DURATION = eINSTANCE.getNoteStmt_Duration();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.RestImpl <em>Rest</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.RestImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getRest()
     * @generated
     */
    EClass REST = eINSTANCE.getRest();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REST__DURATION = eINSTANCE.getRest_Duration();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.ChordImpl <em>Chord</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.ChordImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getChord()
     * @generated
     */
    EClass CHORD = eINSTANCE.getChord();

    /**
     * The meta object literal for the '<em><b>Chord</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CHORD__CHORD = eINSTANCE.getChord_Chord();

    /**
     * The meta object literal for the '<em><b>Notes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHORD__NOTES = eINSTANCE.getChord_Notes();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CHORD__DURATION = eINSTANCE.getChord_Duration();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.RepeatImpl <em>Repeat</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.RepeatImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getRepeat()
     * @generated
     */
    EClass REPEAT = eINSTANCE.getRepeat();

    /**
     * The meta object literal for the '<em><b>Times</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REPEAT__TIMES = eINSTANCE.getRepeat_Times();

    /**
     * The meta object literal for the '<em><b>Blocks</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference REPEAT__BLOCKS = eINSTANCE.getRepeat_Blocks();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.MarkImpl <em>Mark</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.MarkImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getMark()
     * @generated
     */
    EClass MARK = eINSTANCE.getMark();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MARK__LABEL = eINSTANCE.getMark_Label();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.GotoImpl <em>Goto</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.GotoImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getGoto()
     * @generated
     */
    EClass GOTO = eINSTANCE.getGoto();

    /**
     * The meta object literal for the '<em><b>Label</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GOTO__LABEL = eINSTANCE.getGoto_Label();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.NoteValueImpl <em>Note Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.NoteValueImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getNoteValue()
     * @generated
     */
    EClass NOTE_VALUE = eINSTANCE.getNoteValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NOTE_VALUE__VALUE = eINSTANCE.getNoteValue_Value();

    /**
     * The meta object literal for the '{@link org.beathoven.beathoven.impl.DurationImpl <em>Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.beathoven.beathoven.impl.DurationImpl
     * @see org.beathoven.beathoven.impl.BeathovenPackageImpl#getDuration()
     * @generated
     */
    EClass DURATION = eINSTANCE.getDuration();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DURATION__VALUE = eINSTANCE.getDuration_Value();

  }

} //BeathovenPackage
