/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Block</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getBlock()
 * @model
 * @generated
 */
public interface Block extends EObject
{
} // Block
