/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Chord</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.Chord#getChord <em>Chord</em>}</li>
 *   <li>{@link org.beathoven.beathoven.Chord#getNotes <em>Notes</em>}</li>
 *   <li>{@link org.beathoven.beathoven.Chord#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getChord()
 * @model
 * @generated
 */
public interface Chord extends Block
{
  /**
   * Returns the value of the '<em><b>Chord</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Chord</em>' attribute.
   * @see #setChord(String)
   * @see org.beathoven.beathoven.BeathovenPackage#getChord_Chord()
   * @model
   * @generated
   */
  String getChord();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Chord#getChord <em>Chord</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Chord</em>' attribute.
   * @see #getChord()
   * @generated
   */
  void setChord(String value);

  /**
   * Returns the value of the '<em><b>Notes</b></em>' containment reference list.
   * The list contents are of type {@link org.beathoven.beathoven.NoteValue}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Notes</em>' containment reference list.
   * @see org.beathoven.beathoven.BeathovenPackage#getChord_Notes()
   * @model containment="true"
   * @generated
   */
  EList<NoteValue> getNotes();

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(Duration)
   * @see org.beathoven.beathoven.BeathovenPackage#getChord_Duration()
   * @model containment="true"
   * @generated
   */
  Duration getDuration();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Chord#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Duration value);

} // Chord
