/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Goto</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.Goto#getLabel <em>Label</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getGoto()
 * @model
 * @generated
 */
public interface Goto extends Block
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' attribute.
   * @see #setLabel(String)
   * @see org.beathoven.beathoven.BeathovenPackage#getGoto_Label()
   * @model
   * @generated
   */
  String getLabel();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Goto#getLabel <em>Label</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' attribute.
   * @see #getLabel()
   * @generated
   */
  void setLabel(String value);

} // Goto
