/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Instrument</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.Instrument#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getInstrument()
 * @model
 * @generated
 */
public interface Instrument extends Block
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.beathoven.beathoven.BeathovenPackage#getInstrument_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Instrument#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Instrument
