/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Key</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.Key#getNote <em>Note</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getKey()
 * @model
 * @generated
 */
public interface Key extends Block
{
  /**
   * Returns the value of the '<em><b>Note</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Note</em>' containment reference.
   * @see #setNote(NoteValue)
   * @see org.beathoven.beathoven.BeathovenPackage#getKey_Note()
   * @model containment="true"
   * @generated
   */
  NoteValue getNote();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Key#getNote <em>Note</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Note</em>' containment reference.
   * @see #getNote()
   * @generated
   */
  void setNote(NoteValue value);

} // Key
