/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Note Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.NoteStmt#getPitch <em>Pitch</em>}</li>
 *   <li>{@link org.beathoven.beathoven.NoteStmt#getDuration <em>Duration</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getNoteStmt()
 * @model
 * @generated
 */
public interface NoteStmt extends Block
{
  /**
   * Returns the value of the '<em><b>Pitch</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pitch</em>' containment reference.
   * @see #setPitch(NoteValue)
   * @see org.beathoven.beathoven.BeathovenPackage#getNoteStmt_Pitch()
   * @model containment="true"
   * @generated
   */
  NoteValue getPitch();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.NoteStmt#getPitch <em>Pitch</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pitch</em>' containment reference.
   * @see #getPitch()
   * @generated
   */
  void setPitch(NoteValue value);

  /**
   * Returns the value of the '<em><b>Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Duration</em>' containment reference.
   * @see #setDuration(Duration)
   * @see org.beathoven.beathoven.BeathovenPackage#getNoteStmt_Duration()
   * @model containment="true"
   * @generated
   */
  Duration getDuration();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.NoteStmt#getDuration <em>Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Duration</em>' containment reference.
   * @see #getDuration()
   * @generated
   */
  void setDuration(Duration value);

} // NoteStmt
