/**
 * generated by Xtext 2.38.0
 */
package org.beathoven.beathoven;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Repeat</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.beathoven.beathoven.Repeat#getTimes <em>Times</em>}</li>
 *   <li>{@link org.beathoven.beathoven.Repeat#getBlocks <em>Blocks</em>}</li>
 * </ul>
 *
 * @see org.beathoven.beathoven.BeathovenPackage#getRepeat()
 * @model
 * @generated
 */
public interface Repeat extends Block
{
  /**
   * Returns the value of the '<em><b>Times</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Times</em>' attribute.
   * @see #setTimes(int)
   * @see org.beathoven.beathoven.BeathovenPackage#getRepeat_Times()
   * @model
   * @generated
   */
  int getTimes();

  /**
   * Sets the value of the '{@link org.beathoven.beathoven.Repeat#getTimes <em>Times</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Times</em>' attribute.
   * @see #getTimes()
   * @generated
   */
  void setTimes(int value);

  /**
   * Returns the value of the '<em><b>Blocks</b></em>' containment reference list.
   * The list contents are of type {@link org.beathoven.beathoven.Block}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Blocks</em>' containment reference list.
   * @see org.beathoven.beathoven.BeathovenPackage#getRepeat_Blocks()
   * @model containment="true"
   * @generated
   */
  EList<Block> getBlocks();

} // Repeat
