/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BeathovenUiModule extends AbstractBeathovenUiModule {

	public BeathovenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
