/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.beathoven.ui.internal.BeathovenActivator;

public class BeathovenUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return BeathovenActivator.getInstance().getInjector("org.beathoven.Beathoven");
	}

}
