/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBeathovenScopeProvider extends DelegatingScopeProvider {
}
