/*
 * generated by Xtext 2.38.0
 */
package org.beathoven;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BeathovenStandaloneSetup extends BeathovenStandaloneSetupGenerated {

	public static void doSetup() {
		new BeathovenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
