/*
 * generated by Xtext 2.38.0
 */
package org.beathoven.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.xtext.example.beathoven.ui.internal.BeathovenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class BeathovenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(BeathovenActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		BeathovenActivator activator = BeathovenActivator.getInstance();
		return activator != null ? activator.getInjector(BeathovenActivator.ORG_BEATHOVEN_BEATHOVEN) : null;
	}

}
